//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fodraszat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int Id { get; set; }
        public string HairDresser { get; set; }
        public int InvoiceNr { get; set; }
        public string Job { get; set; }
        public string Material { get; set; }
        public System.DateTime Date { get; set; }
        public int Price { get; set; }
        public string Client { get; set; }
    }
}
