//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fodraszat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int Id { get; set; }
        public int ItemNumber { get; set; }
        public string MaterialName { get; set; }
        public int Price { get; set; }
        public int Cost { get; set; }
        public int BoxPrice { get; set; }
    }
}
